terraform {
  required_version = ">= 1.0"

  required_providers {
    infisical = {
      source  = "infisical/infisical"
      version = "~> 0.16"
    }
  }
}

# provider "infisical" and variables are generated by root terragrunt.hcl
