terraform {
  required_version = ">= 1.0"

  required_providers {
    onepassword = {
      source  = "1Password/onepassword"
      version = "~> 2.0"
    }
  }
}

# provider "onepassword" and op variables are generated by root terragrunt.hcl
