repos:
  - repo: local
    hooks:
      - id: check-user
        name: check user value
        entry: scripts/check_user.sh
        language: system
        pass_filenames: false
        always_run: true
