name: Terraform Apply
description: Run terragrunt apply and capture output

inputs:
  working_directory:
    description: "Terraform working directory"
    required: true
  tf_api_token:
    description: "Terraform Cloud API token"
    required: true
  tf_cloud_organization:
    description: "Terraform Cloud organization"
    required: true

outputs:
  apply_text_path:
    description: "Path to apply output file"
    value: ${{ steps.apply.outputs.apply_text_path }}

runs:
  using: composite
  steps:
    - name: Setup
      uses: oda251/dotfiles/.github/actions/terraform-setup@main
      with:
        working_directory: ${{ inputs.working_directory }}
        tf_api_token: ${{ inputs.tf_api_token }}
        tf_cloud_organization: ${{ inputs.tf_cloud_organization }}

    - name: Apply
      id: apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        APPLY_FILE="$(mktemp)"
        terragrunt apply -auto-approve -no-color 2>&1 | tee "$APPLY_FILE"
        echo "apply_text_path=$APPLY_FILE" >> "$GITHUB_OUTPUT"
      env:
        TF_TOKEN_app_terraform_io: ${{ inputs.tf_api_token }}
        TF_CLOUD_ORGANIZATION: ${{ inputs.tf_cloud_organization }}
