name: Terraform Apply
description: Run terragrunt apply and capture output

inputs:
  working_directory:
    description: "Terraform working directory"
    required: true

outputs:
  apply_text_path:
    description: "Path to apply output file"
    value: ${{ steps.apply.outputs.apply_text_path }}

runs:
  using: composite
  steps:
    - name: Setup
      uses: oda251/dotfiles/.github/actions/terraform-setup@main
      with:
        working_directory: ${{ inputs.working_directory }}

    - name: Apply
      id: apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -o pipefail
        APPLY_FILE="$(mktemp)"
        echo "apply_text_path=$APPLY_FILE" >> "$GITHUB_OUTPUT"
        terragrunt apply --terragrunt-no-auto-init -auto-approve -no-color 2>&1 | tee "$APPLY_FILE"
      env:
        TF_TOKEN_app_terraform_io: ${{ env.TF_API_TOKEN }}
        TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORG }}
