# TF-managed: values generated by Terraform

resource "bitwarden_item_login" "grafana_otlp" {
  name     = "grafana-cloud-otlp"
  username = tostring(grafana_cloud_stack.this.id)
  password = local.otlp_token

  field {
    name = "endpoint"
    text = local.otlp_endpoint
  }

  field {
    name = "basic-auth"
    text = local.otlp_basic_auth
  }
}
