# TF-managed: OTLP credentials generated by Terraform, stored in Infisical.

locals {
  generated_secrets = {
    GRAFANA_OTLP_ENDPOINT   = { value = local.otlp_endpoint, comment = "Grafana Cloud OTLP gateway endpoint" }
    GRAFANA_OTLP_BASIC_AUTH = { value = local.otlp_basic_auth, comment = "Base64-encoded instance_id:token for OTLP" }
  }
}

resource "infisical_secret" "generated" {
  for_each = local.generated_secrets

  name         = each.key
  value        = each.value.value
  comment      = each.value.comment
  env_slug     = var.env_slug
  workspace_id = var.infisical_project_id
  folder_path  = "/generated"
}
