# TF-managed: OTLP credentials generated by Terraform, stored in Infisical.

resource "infisical_secret" "otlp_endpoint" {
  name         = "GRAFANA_OTLP_ENDPOINT"
  value        = local.otlp_endpoint
  comment      = "Grafana Cloud OTLP gateway endpoint"
  env_slug     = "prod"
  workspace_id = var.infisical_project_id
  folder_path  = "/generated"
}

resource "infisical_secret" "otlp_basic_auth" {
  name         = "GRAFANA_OTLP_BASIC_AUTH"
  value        = local.otlp_basic_auth
  comment      = "Base64-encoded instance_id:token for OTLP"
  env_slug     = "prod"
  workspace_id = var.infisical_project_id
  folder_path  = "/generated"
}
