terraform {
  required_version = ">= 1.0"

  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "~> 3.0"
    }
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = "~> 0.12"
    }
  }
}

data "bitwarden_item_login" "grafana_cloud" {
  search = "grafana-cloud"
}

provider "grafana" {
  cloud_access_policy_token = one([for f in data.bitwarden_item_login.grafana_cloud.field : f.text if f.name == "api-key"])
}

# provider "bitwarden" and variables are generated by root terragrunt.hcl

variable "grafana_stack_slug" {
  description = "Grafana Cloud stack slug"
  type        = string
}

variable "grafana_stack_region" {
  description = "Grafana Cloud stack region"
  type        = string
  default     = "ap-northeast-0"
}
