terraform {
  required_version = ">= 1.0"

  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "~> 3.0"
    }
    infisical = {
      source  = "infisical/infisical"
      version = "~> 0.16"
    }
  }
}

data "infisical_secrets" "terraform" {
  env_slug     = "prod"
  workspace_id = var.infisical_project_id
  folder_path  = "/terraform"
}

provider "grafana" {
  cloud_access_policy_token = data.infisical_secrets.terraform.secrets["GRAFANA_API_KEY"].value
}

# provider "infisical" and variables are generated by root terragrunt.hcl

variable "grafana_stack_slug" {
  description = "Grafana Cloud stack slug"
  type        = string
}

variable "grafana_stack_region" {
  description = "Grafana Cloud stack region"
  type        = string
  default     = "ap-northeast-0"
}
