terraform {
  required_version = ">= 1.0"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
    infisical = {
      source  = "infisical/infisical"
      version = "~> 0.16"
    }
  }
}

data "infisical_secrets" "terraform" {
  env_slug     = "prod"
  workspace_id = var.infisical_project_id
  folder_path  = "/terraform"
}

provider "github" {
  owner = var.github_owner
  token = data.infisical_secrets.terraform.secrets["GITHUB_PAT"].value
}

# provider "infisical" and variables are generated by root terragrunt.hcl

variable "github_owner" {
  description = "GitHub organization or user"
  type        = string
}
