terraform {
  required_version = ">= 1.0"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
    infisical = {
      source  = "infisical/infisical"
      version = "~> 0.16"
    }
  }
}

# data "infisical_secrets" "terraform" is generated by root terragrunt.hcl

provider "github" {
  owner = var.github_owner
  token = data.infisical_secrets.terraform.secrets["GITHUB_PAT"].value
}

variable "github_owner" {
  description = "GitHub organization or user"
  type        = string
}

