terraform {
  required_version = ">= 1.0"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
    onepassword = {
      source  = "1Password/onepassword"
      version = "~> 2.0"
    }
  }
}

provider "github" {
  owner = var.github_owner
  token = data.onepassword_item.github_pat.password
}

# provider "onepassword" and op variables are generated by root terragrunt.hcl
# data "onepassword_item" resources are defined in secrets.tf

variable "github_owner" {
  description = "GitHub organization or user"
  type        = string
}
