gui:
  editor:
    command: nvim
  pagers:
    colorArg: always
    pager: delta --dark --paging=never
merging:
  manualCommit: false
  editorCommand: 'nvim -d -c "wincmd J" "$LOCAL" "$MERGED" "$REMOTE"'
