[[mgr.prepend_keymap]]
on = [ "g", "i" ]
run = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on = [ "c", "a" ]
run = "plugin ops -- copy-contents"
desc = "copy file contents"

[[mgr.prepend_keymap]]
on = [ "c", "g" ]
run = "plugin ops -- copy-github-link"
desc = "copy GitHub link"

[[mgr.prepend_keymap]]
on = "<Space>"
run = "plugin ops -- git-add"
desc = "toggle git stage"

[[mgr.prepend_keymap]]
on = "`"
run = "plugin ops -- run-zsh-command"
desc = "run zsh command"
