terraform {
  required_version = ">= 1.0"

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 3.0"
    }
    infisical = {
      source  = "infisical/infisical"
      version = "~> 0.16"
    }
  }
}

# data "infisical_secrets" "terraform" is generated by root terragrunt.hcl

provider "newrelic" {
  api_key    = data.infisical_secrets.terraform.secrets["NEW_RELIC_API_KEY"].value
  account_id = data.infisical_secrets.terraform.secrets["NEW_RELIC_ACCOUNT_ID"].value
  region     = var.newrelic_region
}

variable "newrelic_region" {
  description = "New Relic region (US or EU)"
  type        = string
  default     = "US"
}
