name: CI
description: Run setup, lint, and test via Make

runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: make setup

    - name: Lint
      shell: bash
      run: make lint

    - name: Test
      shell: bash
      run: make test
