name: Terraform Plan
description: Run terragrunt plan

inputs:
  working_directory:
    description: "Terraform working directory"
    required: true
  tf_api_token:
    description: "Terraform Cloud API token"
    required: true
  tf_cloud_organization:
    description: "Terraform Cloud organization"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v3
      with:
        terragrunt-version: latest

    - name: Plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terragrunt plan -no-color
      env:
        TF_TOKEN_app_terraform_io: ${{ inputs.tf_api_token }}
        TF_CLOUD_ORGANIZATION: ${{ inputs.tf_cloud_organization }}
