onboarding = false
auto_switch = false

[theme]
name = "tokyo-night"

[keys]
prefix = "ctrl+g"

new_workspace    = ["prefix+t"]
new_tab          = ["prefix+ctrl+t"]
split_vertical   = ["prefix+alt+t"]
split_horizontal = ["prefix+minus"]
close_pane       = ["prefix+w"]
resize_mode      = ["prefix+n"]
rename_pane      = ["prefix+alt+r"]
zoom             = ["prefix+z"]

previous_tab       = ["ctrl+left"]
next_tab           = ["ctrl+right"]
previous_workspace = ["ctrl+up"]
next_workspace     = ["ctrl+down"]

focus_pane_left  = ["ctrl+alt+left"]
focus_pane_down  = ["ctrl+alt+down"]
focus_pane_up    = ["ctrl+alt+up"]
focus_pane_right = ["ctrl+alt+right"]
