name: CI

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Test
        run: make test
